theme: minima

exclude:
  - bounds/old_bounds/README.md


header_pages:
  - pages/overview.md
  - bounds/bounds.md
  - updates.md
  - papers.md

plugins: [jekyll-titles-from-headings]

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 