theme: minima

exclude:
  - bounds/old_bounds/README.md

header_pages:
  - bounds/README.md
  - UPDATES.md
  - PAPERS.md

plugins: [jekyll-titles-from-headings]

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
